# Generated by Django 2.2 on 2019-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='video_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
